-- data pulled from release-5-2-1/work/db/rice-data/bootstrap/krim_perm_t.csv - new names to prevent duplicates

UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Claim Electronic Payment CTRL' WHERE PERM_ID = '1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Customer customerTaxNbr' WHERE PERM_ID = '10';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document REQS PreRoute' WHERE PERM_ID = '100';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document PO PreRoute' WHERE PERM_ID = '101';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document AP PreRoute' WHERE PERM_ID = '102';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document RCV PreRoute' WHERE PERM_ID = '103';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Claim Electronic Payment' WHERE PERM_ID = '107';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Error Correct Document KFST' WHERE PERM_ID = '108';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) customerLoadInputFileType' WHERE PERM_ID = '11';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Administer Routing for Document KFST' WHERE PERM_ID = '1100';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Administer Routing for Document KFS' WHERE PERM_ID = '113';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document KFS' WHERE PERM_ID = '114';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document KFS' WHERE PERM_ID = '115';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document FSSM' WHERE PERM_ID = '116';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document BANK' WHERE PERM_ID = '117';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Assign Role KFS*' WHERE PERM_ID = '119';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen KFS-AR' WHERE PERM_ID = '12';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Grant Permission KFS*' WHERE PERM_ID = '120';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Grant Responsibility KFS*' WHERE PERM_ID = '121';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Populate Group KFS*' WHERE PERM_ID = '122';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Bank bankAccountNumber' WHERE PERM_ID = '128';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Inquire Into Records KFS*' WHERE PERM_ID = '129';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records KFS*' WHERE PERM_ID = '130';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Maintain System Parameter KFS*' WHERE PERM_ID = '131';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Batch Job KFS*' WHERE PERM_ID = '132';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document KFS' WHERE PERM_ID = '133';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Partial Unmask Field Bank bankAccountNumber' WHERE PERM_ID = '134';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen KFS*' WHERE PERM_ID = '135';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PVEN' WHERE PERM_ID = '136';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field VendorDetail vendorHeader.vendorTaxNumber' WHERE PERM_ID = '137';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field VendorDetail vendorHeader.vendorTaxNumber' WHERE PERM_ID = '138';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section VendorDetail vendorContracts' WHERE PERM_ID = '139';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen KFS-CAB' WHERE PERM_ID = '15';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document MPAY' WHERE PERM_ID = '16';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Save Document KFS' WHERE PERM_ID = '169';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document BCIE' WHERE PERM_ID = '17';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CAM' WHERE PERM_ID = '18';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section VendorDetail vendorCommodities' WHERE PERM_ID = '184';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document CMD PreRoute' WHERE PERM_ID = '185';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field DisbursementPayee taxNumber' WHERE PERM_ID = '187';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines INV Account sourceAccountingLines' WHERE PERM_ID = '188';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines SB PreRoute sourceAccountingLines' WHERE PERM_ID = '189';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CAMM' WHERE PERM_ID = '19';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines FP Account sourceAccountingLines' WHERE PERM_ID = '190';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines FP Account targetAccountingLines' WHERE PERM_ID = '191';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines DV Campus sourceAccountingLines.financialObjectCode' WHERE PERM_ID = '192';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines DV Tax sourceAccountingLines.amount' WHERE PERM_ID = '193';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines DV Travel sourceAccountingLines.amount' WHERE PERM_ID = '194';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines DV PaymentMethod sourceAccountingLines.amount' WHERE PERM_ID = '195';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines LD Account targetAccountingLines' WHERE PERM_ID = '196';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines ST targetAccountingLines.financialObjectCode' WHERE PERM_ID = '197';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines PUR Account items.sourceAccountingLines' WHERE PERM_ID = '198';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines AP Account items.sourceAccountingLines' WHERE PERM_ID = '199';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Negative Payments' WHERE PERM_ID = '20';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines MPAY Account sourceAccountingLines' WHERE PERM_ID = '200';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document PRPL' WHERE PERM_ID = '201';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document ST' WHERE PERM_ID = '202';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document ST' WHERE PERM_ID = '205';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document ECD detailTabEntry' WHERE PERM_ID = '206';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document ECD summaryTabEntry' WHERE PERM_ID = '207';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document DV taxEntry' WHERE PERM_ID = '209';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Merge' WHERE PERM_ID = '21';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document DV frnEntry' WHERE PERM_ID = '210';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document DV wireEntry' WHERE PERM_ID = '211';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document DV travelEntry' WHERE PERM_ID = '212';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document AP editPreExtract' WHERE PERM_ID = '217';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Override CAPITALIZATION_LIMIT_AMOUNT' WHERE PERM_ID = '22';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code KFST' WHERE PERM_ID = '220';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document BC' WHERE PERM_ID = '225';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Import / Export Payrate' WHERE PERM_ID = '228';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Unlock' WHERE PERM_ID = '229';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Raze' WHERE PERM_ID = '23';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Override Transfer Impacting Open Effort Certification' WHERE PERM_ID = '230';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Partial Unmask Field PayeeACHAccount bankAccountNumber' WHERE PERM_ID = '233';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field ACHBank bankRoutingNumber' WHERE PERM_ID = '234';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field PayeeACHAccount bankAccountNumber' WHERE PERM_ID = '235';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field PayeeACHAccount bankRoutingNumber' WHERE PERM_ID = '236';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines FP PreRoute sourceAccountingLines' WHERE PERM_ID = '238';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines FP PreRoute targetAccountingLines' WHERE PERM_ID = '239';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Retire Multiple' WHERE PERM_ID = '24';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines LD PreRoute targetAccountingLines' WHERE PERM_ID = '240';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines PUR PreRoute items.sourceAccountingLines' WHERE PERM_ID = '241';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines AP PreRoute items.sourceAccountingLines' WHERE PERM_ID = '242';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines INV PreRoute sourceAccountingLines' WHERE PERM_ID = '243';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines CAM PreRoute sourceAccountingLines' WHERE PERM_ID = '244';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CUS' WHERE PERM_ID = '245';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document INV' WHERE PERM_ID = '246';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document BC' WHERE PERM_ID = '247';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) OOPT FALSE' WHERE PERM_ID = '248';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) OOPT TRUE' WHERE PERM_ID = '249';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Retire Non-Movable Assets' WHERE PERM_ID = '25';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) CASM FALSE' WHERE PERM_ID = '250';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen KFS-BC' WHERE PERM_ID = '251';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records BatchJobStatus' WHERE PERM_ID = '256';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.module.purap.web.struts.B2BAction' WHERE PERM_ID = '257';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PREQ Invoice Image' WHERE PERM_ID = '258';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Separate' WHERE PERM_ID = '26';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PREQ Invoice Image' WHERE PERM_ID = '260';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Delete Note / Attachment KFS FALSE' WHERE PERM_ID = '263';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document BC F' WHERE PERM_ID = '266';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document PREQ R' WHERE PERM_ID = '268';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document PRAP' WHERE PERM_ID = '269';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Transfer Non-Movable Assets' WHERE PERM_ID = '27';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.module.purap.document.web.struts.PrintAction' WHERE PERM_ID = '270';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.sys.web.struts.ElectronicFundTransferAction' WHERE PERM_ID = '271';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PO printPurchaseOrder' WHERE PERM_ID = '272';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PO previewPrintPurchaseOrder' WHERE PERM_ID = '273';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PO assignSensitiveData' WHERE PERM_ID = '274';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PO resendPurchaseOrder' WHERE PERM_ID = '275';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PREQ requestPaymentRequestCancel' WHERE PERM_ID = '276';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PREQ paymentRequestHoldCancelRemoval' WHERE PERM_ID = '277';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines LD PreRoute sourceAccountingLines' WHERE PERM_ID = '279';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Acquisition Type "New"' WHERE PERM_ID = '28';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines PCDO AccountFullEdit sourceAccountingLines' WHERE PERM_ID = '280';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines PCDO AccountFullEdit targetAccountingLines' WHERE PERM_ID = '281';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document AP managerCancel' WHERE PERM_ID = '282';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document AP processorCancel' WHERE PERM_ID = '283';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document ACM' WHERE PERM_ID = '284';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen KFS-PDP' WHERE PERM_ID = '285';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document PREQ requestPaymentRequestHold' WHERE PERM_ID = '286';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.gl.web.struts.BalanceInquiryAction' WHERE PERM_ID = '287';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Restricted Retirement Reason' WHERE PERM_ID = '29';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document EIRT' WHERE PERM_ID = '291';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) electronicInvoiceInputFileType' WHERE PERM_ID = '292';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document CM requestVendorCreditMemoHold' WHERE PERM_ID = '293';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document CM vendorCreditMemoHoldRemoval' WHERE PERM_ID = '294';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Organization Salary Setting' WHERE PERM_ID = '295';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Appointment Funding' WHERE PERM_ID = '296';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Appointment Funding Amounts' WHERE PERM_ID = '297';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document ARM' WHERE PERM_ID = '3';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.sys.web.struts.KualiBalanceInquiryReportMenuAction' WHERE PERM_ID = '301';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document DEPR' WHERE PERM_ID = '302';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records KFS-CAB' WHERE PERM_ID = '303';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Inquire Into Records KFS-CAB' WHERE PERM_ID = '304';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) IICO FALSE' WHERE PERM_ID = '305';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines REQS Initiator items.sourceAccountingLines' WHERE PERM_ID = '308';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PO Contracts' WHERE PERM_ID = '313';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PO Contracts' WHERE PERM_ID = '314';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PO Contract Ammendments' WHERE PERM_ID = '315';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PO Contract Ammendments' WHERE PERM_ID = '316';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PO Quotes' WHERE PERM_ID = '317';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PO Quotes' WHERE PERM_ID = '318';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PO RFPs' WHERE PERM_ID = '319';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset organizationOwnerChartOfAccountsCode' WHERE PERM_ID = '32';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PO RFPs' WHERE PERM_ID = '320';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PO RFP Responses' WHERE PERM_ID = '321';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PO RFP Responses' WHERE PERM_ID = '322';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment PO Other - Restricted' WHERE PERM_ID = '323';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment PO Other - Restricted' WHERE PERM_ID = '324';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Note / Attachment CM Credit Memo Image' WHERE PERM_ID = '325';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Note / Attachment CM Credit Memo Image' WHERE PERM_ID = '326';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Maintain Asset Location' WHERE PERM_ID = '327';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines REQS Organization items.sourceAccountingLines' WHERE PERM_ID = '328';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.fp.document.web.struts.CashManagementStatusAction' WHERE PERM_ID = '329';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset organizationOwnerAccountNumber' WHERE PERM_ID = '33';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.fp.document.web.struts.DepositWizardAction' WHERE PERM_ID = '330';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.fp.web.struts.CashDrawerCorrectionAction' WHERE PERM_ID = '331';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field VendorDetail vendorHeader.vendorTaxTypeCode' WHERE PERM_ID = '335';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset capitalAssetInServiceDate' WHERE PERM_ID = '34';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset capitalAssetTypeCode' WHERE PERM_ID = '342';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset capitalAssetDescription' WHERE PERM_ID = '343';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset campusTagNumber' WHERE PERM_ID = '344';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Perform Custom Maintenance Document Function calculateEqualSourceAmountsButton' WHERE PERM_ID = '346';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Perform Custom Maintenance Document Function calculateSeparateSourceRemainingAmountButton' WHERE PERM_ID = '347';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset oldTagNumber' WHERE PERM_ID = '348';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document IICO' WHERE PERM_ID = '349';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset agencyNumber' WHERE PERM_ID = '35';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CR' WHERE PERM_ID = '350';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Serve As Account Supervisor' WHERE PERM_ID = '351';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Serve As Fiscal Officer' WHERE PERM_ID = '352';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Serve As Fiscal Officer Delegate' WHERE PERM_ID = '353';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen org.kuali.kfs.fp.document.web.struts.DisbursementVoucherHelpAction' WHERE PERM_ID = '354';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines POA NewUnorderedItems items.sourceAccountingLines' WHERE PERM_ID = '355';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CM' WHERE PERM_ID = '356';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document APP' WHERE PERM_ID = '357';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines DV Travel sourceAccountingLines.financialObjectCode' WHERE PERM_ID = '358';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset vendorName' WHERE PERM_ID = '36';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document INVR' WHERE PERM_ID = '360';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CDS' WHERE PERM_ID = '361';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Batch File(s) KFS*' WHERE PERM_ID = '362';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records KFS-PDP PurchasingPaymentDetail' WHERE PERM_ID = '363';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field VendorDetail vendorHeader.vendorTaxTypeCode' WHERE PERM_ID = '364';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document PREQ P' WHERE PERM_ID = '365';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document PREQ F' WHERE PERM_ID = '366';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document CM P' WHERE PERM_ID = '367';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document CM F' WHERE PERM_ID = '368';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) OADF FALSE' WHERE PERM_ID = '369';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset oldTagNumber' WHERE PERM_ID = '37';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines INV Recurrence sourceAccountingLines.invoiceItemDescription' WHERE PERM_ID = '371';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code CMD' WHERE PERM_ID = '372';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code PREQ' WHERE PERM_ID = '373';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code DV' WHERE PERM_ID = '374';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records Pretag' WHERE PERM_ID = '375';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) PTAG' WHERE PERM_ID = '376';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit When Tagged Prior Fiscal Year' WHERE PERM_ID = '377';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document IdentityManagementGroupDocument' WHERE PERM_ID = '379';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset governmentTagNumber' WHERE PERM_ID = '38';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document GORV' WHERE PERM_ID = '380';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document FSSM AdHoc R' WHERE PERM_ID = '382';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document KFSM AdHoc R' WHERE PERM_ID = '383';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) collectorFlatFileInputFileType' WHERE PERM_ID = '385';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field PaymentDetail achBankRoutingNbr' WHERE PERM_ID = '386';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field PaymentDetail achBankAccountNbr' WHERE PERM_ID = '387';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset nationalStockNumber' WHERE PERM_ID = '39';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Ad Hoc Review Document KFS A' WHERE PERM_ID = '390';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Ad Hoc Review Document KFS F' WHERE PERM_ID = '391';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Ad Hoc Review Document KFS K' WHERE PERM_ID = '392';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Asset financialObjectSubTypeCode' WHERE PERM_ID = '40';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) assetBarcodeInventoryInputFileType' WHERE PERM_ID = '42';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset replacementAmount' WHERE PERM_ID = '43';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset estimatedSellingPrice' WHERE PERM_ID = '44';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset conditionCode' WHERE PERM_ID = '46';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset landCountyName' WHERE PERM_ID = '47';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset landAcreageSize' WHERE PERM_ID = '48';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Field Asset landParcelNumber' WHERE PERM_ID = '49';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document APP' WHERE PERM_ID = '5';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CLOS' WHERE PERM_ID = '51';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PRPL' WHERE PERM_ID = '52';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Inquiry or Maintenance Document Section Proposal proposalResearchRisks' WHERE PERM_ID = '54';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document GOBJ' WHERE PERM_ID = '55';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document ORGR' WHERE PERM_ID = '56';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Inactive Account' WHERE PERM_ID = '58';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Serve As Account Manager' WHERE PERM_ID = '59';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CTRL' WHERE PERM_ID = '6';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field SubAccount a21SubAccount' WHERE PERM_ID = '60';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Organization organizationPlantChartCode' WHERE PERM_ID = '61';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Organization organizationPlantAccountNumber' WHERE PERM_ID = '62';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Organization campusPlantChartCode' WHERE PERM_ID = '63';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field Organization campusPlantAccountNumber' WHERE PERM_ID = '64';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document ECD' WHERE PERM_ID = '65';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Claim Electronic Payment DI' WHERE PERM_ID = '66';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Claim Electronic Payment YEDI' WHERE PERM_ID = '67';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CMD' WHERE PERM_ID = '69';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document SB' WHERE PERM_ID = '70';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document JV' WHERE PERM_ID = '71';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PCDO' WHERE PERM_ID = '72';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field ProcurementCardHolder transactionCreditCardNumber' WHERE PERM_ID = '73';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) procurementCardInputFileType' WHERE PERM_ID = '74';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document GLCP' WHERE PERM_ID = '75';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) collectorXmlInputFileType' WHERE PERM_ID = '76';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) enterpriseFeederFileSetType' WHERE PERM_ID = '77';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document LLJV' WHERE PERM_ID = '78';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document LLCP' WHERE PERM_ID = '79';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document AR' WHERE PERM_ID = '8';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Set as Immmediate Pay' WHERE PERM_ID = '80';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PDSM' WHERE PERM_ID = '81';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Cancel Payment' WHERE PERM_ID = '82';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Format' WHERE PERM_ID = '83';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Hold Payment / Remove Non-Tax Payment Hold' WHERE PERM_ID = '84';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Remove Format Lock' WHERE PERM_ID = '86';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Remove Payment Tax Hold' WHERE PERM_ID = '87';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Inquire Into Records KFS-PDP' WHERE PERM_ID = '88';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records KFS-PDP' WHERE PERM_ID = '89';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Customer customerTaxNbr' WHERE PERM_ID = '9';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) paymentInputFileType' WHERE PERM_ID = '90';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document PREQ' WHERE PERM_ID = '91';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document REQS' WHERE PERM_ID = '92';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PUR' WHERE PERM_ID = '93';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PO' WHERE PERM_ID = '94';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document POC' WHERE PERM_ID = '95';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PORT' WHERE PERM_ID = '96';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document PREQ' WHERE PERM_ID = '97';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document RCV' WHERE PERM_ID = '98';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document EIRT' WHERE PERM_ID = '99';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Copy Document KFS' WHERE PERM_ID = '1101';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Add Message to Route Log KFS' WHERE PERM_ID = '1103';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) laborEnterpriseFeederFileSetType' WHERE PERM_ID = '1105';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document ACCT' WHERE PERM_ID = '1106';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document AccessSecuritySimpleMaintenanceDocument' WHERE PERM_ID = 'KFSSEC6001';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records KFS-SEC' WHERE PERM_ID = 'KFSSEC6002';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Inquire Into Records KFS-SEC' WHERE PERM_ID = 'KFSSEC6003';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document AccessSecuritySimpleMaintenanceDocument PreRoute' WHERE PERM_ID = 'KFSSEC6004';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TicklerMaintenanceDocument' WHERE PERM_ID = 'KFSENDOW6005';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Ad Hoc Review Document TicklerMaintenanceDocument F' WHERE PERM_ID = 'KFSENDOW6007';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Endowment Reporting Screens org.kuali.kfs.module.endow.web.struts.TrialBalanceAction' WHERE PERM_ID = 'KFSENDOW6008';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Endowment Reporting Screens org.kuali.kfs.module.endow.web.struts.TransactionStatementAction' WHERE PERM_ID = 'KFSENDOW6009';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Endowment Reporting Screens org.kuali.kfs.module.endow.web.struts.TransactionSummaryAction' WHERE PERM_ID = 'KFSENDOW6010';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Endowment Reporting Screens org.kuali.kfs.module.endow.web.struts.AssetStatementAction' WHERE PERM_ID = 'KFSENDOW6011';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Customer CSV Files' WHERE PERM_ID = 'KFSAR6012';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Unmask PO # On PO Document' WHERE PERM_ID = 'KFSPURAP6940';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Labor Enterprise Feed Batch Files' WHERE PERM_ID = 'KFSLD6987';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Accounting Period' WHERE PERM_ID = 'KFSSYS7145a';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Accounting Period' WHERE PERM_ID = 'KFSSYS7145b';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Allow DV Immediate Disbursement' WHERE PERM_ID = 'KFSSYS6007';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit APP Document-PreRoute' WHERE PERM_ID = 'KFSAR6732';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Invoice Processing Organization' WHERE PERM_ID = 'KFSAR5340P';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Maintain ACH Accounts' WHERE PERM_ID = 'KFSMI6886-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Lookup ACH Accounts' WHERE PERM_ID = 'KFSMI6886-PRM2';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate ACH Account Document' WHERE PERM_ID = 'KFSMI6886-PRM3';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Fringe Benefit Inquiry' WHERE PERM_ID = 'KFSMI7041-PRM';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Vendor Exclude File Upload Screen' WHERE PERM_ID = 'KFSCNTRB162-PRM';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload semaphoreInputFileTypeError' WHERE PERM_ID = 'KFSCNTRB199-P1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Administer Batch File KFS-SYS batchContainer' WHERE PERM_ID = 'KFSCNTRB199-P2';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section SubAccount indirectCostRecoveryAccounts' WHERE PERM_ID = 'KFSMI8342-PRM';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Acct Lines PO Pur Process itemssourceAccountingLines' WHERE PERM_ID = 'KFSMI8906-PRM';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines PUR Tax itemsourceAccountingLines' WHERE PERM_ID = 'KFSMI8944-PRM';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Recall Document FP' WHERE PERM_ID = 'KFSMI8893-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Send Complete Request KFS' WHERE PERM_ID = 'KFSMI9071-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Access Locked Module' WHERE PERM_ID = 'KFSCNTRB65-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Super User Approve Single Action Request KFS' WHERE PERM_ID = 'KFSMI9598-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Super User Approve Document KFS' WHERE PERM_ID = 'KFSMI9598-PRM2';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Super User Disapprove Document KFS' WHERE PERM_ID = 'KFSMI9598-PRM3';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) lockboxInputFileType' WHERE PERM_ID = 'KFSCNTRB1343-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Super User Disapprove PREQ Document' WHERE PERM_ID = 'PREQ_SU_DISAPPROVE';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Ad Hoc Review Document KFS C' WHERE PERM_ID = 'KFSCNTRB-1558-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Research Participant CSV Files' WHERE PERM_ID = 'KFSCNTRB705-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Payment Detail Payee Name' WHERE PERM_ID = 'KFSCNTRB705-PRM2';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Payment Detail Payee Street' WHERE PERM_ID = 'KFSCNTRB705-PRM3';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Payment Detail Payee City' WHERE PERM_ID = 'KFSCNTRB705-PRM4';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Payment Detail Payee State' WHERE PERM_ID = 'KFSCNTRB705-PRM5';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field Payment Detail Payee Zip Code' WHERE PERM_ID = 'KFSCNTRB705-PRM6';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Download Research Participant Check File(s)' WHERE PERM_ID = 'KFSCNTRB705-PRM7';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Trial Balance Screen' WHERE PERM_ID = 'KFSCNTRB-762-PRM1';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Amend TA' WHERE PERM_ID = 'KFS10282';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Hold TA' WHERE PERM_ID = 'KFS10283';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Remove Hold TA' WHERE PERM_ID = 'KFS10284';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Cancel TA' WHERE PERM_ID = 'KFS10285';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Close TA' WHERE PERM_ID = 'KFS10286';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Return to Fiscal Officer' WHERE PERM_ID = 'KFS10287';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TT Account sourceAccountingLines' WHERE PERM_ID = 'KFS10288';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TravelAuthorizationDocument cellPhoneNumber' WHERE PERM_ID = 'KFS10290';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TravelerDetailEmergencyContact contactRelationTypeCode' WHERE PERM_ID = 'KFS10291';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TravelerDetailEmergencyContact contactName' WHERE PERM_ID = 'KFS10292';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TravelerDetailEmergencyContact phoneNumber' WHERE PERM_ID = 'KFS10293';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TravelerDetailEmergencyContact emailAddress' WHERE PERM_ID = 'KFS10294';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfileEmergencyContact contactRelationTypeCode' WHERE PERM_ID = 'KFS10295';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfileEmergencyContact contactName' WHERE PERM_ID = 'KFS10296';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfileEmergencyContact phoneNumber' WHERE PERM_ID = 'KFS10297';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfileEmergencyContact emailAddress' WHERE PERM_ID = 'KFS10298';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Calculate TA' WHERE PERM_ID = 'KFS10299';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Inactivate TEM Profile' WHERE PERM_ID = 'KFS10302';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section TemProfile TemProfileAdministrator' WHERE PERM_ID = 'KFS10304';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfile dateOfBirth' WHERE PERM_ID = 'KFS10307';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfile gender' WHERE PERM_ID = 'KFS10308';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfile driversLicenseNumber' WHERE PERM_ID = 'KFS10309';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfile driversLicenseExpDate' WHERE PERM_ID = 'KFS10310';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Unmask Field TemProfile driversLicenseState' WHERE PERM_ID = 'KFS10311';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Partial Unmask Field TemProfileAccount accountNumber' WHERE PERM_ID = 'KFS10312';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) perDiemTxtInputFileType' WHERE PERM_ID = 'KFS10313';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) perDiemXmlInputFileType' WHERE PERM_ID = 'KFS10314';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Taxable Indicator' WHERE PERM_ID = 'KFS10315';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) agencyDataXmlInputFileType' WHERE PERM_ID = 'KFS10316';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Upload Batch Input File(s) creditCardDataXmlInputFileType' WHERE PERM_ID = 'KFS10317';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TR Account sourceAccountingLines' WHERE PERM_ID = 'KFS10318';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TR Travel sourceAccountingLines' WHERE PERM_ID = 'KFS10319';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TA Travel sourceAccountingLines' WHERE PERM_ID = 'KFS10320';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document TXRF' WHERE PERM_ID = 'KFS10321';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TXRF' WHERE PERM_ID = 'KFS10322';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TAAR' WHERE PERM_ID = 'KFS10323';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines ENT EntertainmentManager sourceAccountingLines' WHERE PERM_ID = 'KFS10325';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines RELO MovingAndRelocationManager sourceAccountingLines' WHERE PERM_ID = 'KFS10326';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CRM' WHERE PERM_ID = 'KFS10327';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document TT' WHERE PERM_ID = 'KFS10328';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TT PreRoute sourceAccountingLines' WHERE PERM_ID = 'KFS10329';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document TT PreRoute' WHERE PERM_ID = 'KFS10330';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TR PreRoute sourceAccountingLines' WHERE PERM_ID = 'KFS10331';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Full Edit Agency Data' WHERE PERM_ID = 'KFS10332';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section AgencyStagingData airline' WHERE PERM_ID = 'KFS10333';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section AgencyStagingData lodging' WHERE PERM_ID = 'KFS10334';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Section AgencyStagingData rentalcar' WHERE PERM_ID = 'KFS10335';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Look Up Records TemProfileAccount' WHERE PERM_ID = 'KFS10336';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document ENT' WHERE PERM_ID = 'KFS10337';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document ENT PreRoute' WHERE PERM_ID = 'KFS10338';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document RELO' WHERE PERM_ID = 'KFS10339';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Document RELO PreRoute' WHERE PERM_ID = 'KFS10340';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CTAP' WHERE PERM_ID = 'KFS10341';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document CCIE' WHERE PERM_ID = 'KFS10342';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document INV' WHERE PERM_ID = 'KFS10372';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document CRM' WHERE PERM_ID = 'KFS10373';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TA advancePolicyEntry' WHERE PERM_ID = 'KFS10387';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData importBy' WHERE PERM_ID = 'KFS10397';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData agencyDataId' WHERE PERM_ID = 'KFS10398';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData otherCompanyName' WHERE PERM_ID = 'KFS10399';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData tripTravelerTypeId' WHERE PERM_ID = 'KFS10400';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData otherAmount' WHERE PERM_ID = 'KFS10401';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData travelerName' WHERE PERM_ID = 'KFS10402';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData travelerNetworkId' WHERE PERM_ID = 'KFS10403';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData tripExpenseAmount' WHERE PERM_ID = 'KFS10404';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Maintenance Document Field AgencyStagingData tripArrangerName' WHERE PERM_ID = 'KFS10405';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'View Record TravelerProfileForLookup' WHERE PERM_ID = 'KFS10445';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TMCP' WHERE PERM_ID = 'KFS10451';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TT' WHERE PERM_ID = 'KFS10454';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TT expenseTaxableEntry' WHERE PERM_ID = 'KFS10470';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TA Account advanceAccountingLines' WHERE PERM_ID = 'KFS10503';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TA Travel advanceAccountingLines' WHERE PERM_ID = 'KFS10508';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TT Travel sourceAccountingLines' WHERE PERM_ID = 'KFS10513';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create / Maintain Record(s) TTP' WHERE PERM_ID = 'KFS10518';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Copy Document TRV' WHERE PERM_ID = 'KFS10544';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TTA' WHERE PERM_ID = 'KFS10668';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TTA travelerEntry' WHERE PERM_ID = 'KFS10698';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Blanket Approve Document DV' WHERE PERM_ID = 'KFS10715';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code ENT' WHERE PERM_ID = 'KFS10721';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code RELO' WHERE PERM_ID = 'KFS10722';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Bank Code TRV' WHERE PERM_ID = 'KFS10723';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TTP' WHERE PERM_ID = 'KFS10730';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit My TEM Profile' WHERE PERM_ID = 'KFS10733';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit All TEM Profiles' WHERE PERM_ID = 'KFS10735';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Create All TEM Profiles' WHERE PERM_ID = 'KFS10738';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TT expenseLimitEntry' WHERE PERM_ID = 'KFS10746';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TT frnEntry' WHERE PERM_ID = 'KFS10754';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TT wireEntry' WHERE PERM_ID = 'KFS10758';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines TR PaymentMethod sourceAccountingLines.amount' WHERE PERM_ID = 'KFS10762';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TRV conversionRateEntry' WHERE PERM_ID = 'KFS10767';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document ENT conversionRateEntry' WHERE PERM_ID = 'KFS10773';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document RELO conversionRateEntry' WHERE PERM_ID = 'KFS10779';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines ENT PaymentMethod sourceAccountingLines.amount' WHERE PERM_ID = 'KFS10785';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Modify Accounting Lines RELO PaymentMethod sourceAccountingLines.amount' WHERE PERM_ID = 'KFS10790';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Transactional Document TT immediateDisbursementEntryMode' WHERE PERM_ID = 'KFS10798';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Initiate Document TAA' WHERE PERM_ID = 'KFS10804';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Report' WHERE PERM_ID = 'KFS10811';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Open Document INV' WHERE PERM_ID = 'KFS10817';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Use Screen KFS-AR CustomerOpenItemReportAction' WHERE PERM_ID = 'KFS10821';
UPDATE KULOWNER.KRIM_PERM_T SET NM = 'Edit Capital Asset Info' WHERE PERM_ID = 'KFS10838';

