-- =======================================================================================================================
-- UAF-31 : Database Update Scripts
-- =======================================================================================================================

--remove unused Parameters:
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_TYPE';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_DELIMETER';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_HEADER_IND';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_FOOTER_IND';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_COL_LENGTHS';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_FOOTER_COL_LENGTHS';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_FILE_HEADER_COL_LENGTHS';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_ACCT_NUM_COL';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_CHECK_AMT_COL';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_CHECK_NUM_COL';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_CHECK_DATE_COL';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_STATUS_COL';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_ACCT_NUM_COL_HEADER_IND';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_AMOUNT_DECIMAL_IND';
DELETE FROM KRCR_PARM_T WHERE NMSPC_CD='KUALI-CR' AND CMPNT_CD='CheckReconciliationImportStep' AND PARM_NM='CR_CHECK_DATE_FORMAT';

