-- ============================================================================
-- UAF-6457 : Create new responsibility for PREQ to force action for AP tax Specialist on Tax route node. Subtask of (UAF-92)
-- ============================================================================
-- Adding new responsibility on PREQ to force action for the AP group on the Tax route node.
INSERT INTO KRIM_RSP_T (RSP_ID, RSP_TMPL_ID, NM, NMSPC_CD, VER_NBR, DESC_TXT, OBJ_ID, ACTV_IND) VALUES (KRIM_RSP_ID_S.NEXTVAL, '1', 'Review PREQ Tax', 'KFS-SYS', '1', 'Responsibility for tax purposes review on PREQ document.', 'UAF-6457-1', 'Y');
COMMIT;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL, VER_NBR, OBJ_ID) VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NM='Review PREQ Tax' AND OBJ_ID='UAF-6457-1'), '7', '41', 'false', '1', 'UAF-6457-2');
COMMIT;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL, VER_NBR, OBJ_ID) VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NM='Review PREQ Tax' AND OBJ_ID='UAF-6457-1'), '7', '13', 'PREQ', '1', 'UAF-6457-3');
COMMIT;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL, VER_NBR, OBJ_ID) VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NM='Review PREQ Tax' AND OBJ_ID='UAF-6457-1'), '7', '16', 'Tax', '1', 'UAF-6457-4');
COMMIT;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL, VER_NBR, OBJ_ID) VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NM='Review PREQ Tax' AND OBJ_ID='UAF-6457-1'), '7', '40', 'false', '1', 'UAF-6457-5');
COMMIT;
INSERT INTO KRIM_ROLE_RSP_T (ROLE_RSP_ID,	OBJ_ID,	VER_NBR,	ROLE_ID,	RSP_ID,	ACTV_IND) VALUES (KRIM_ROLE_RSP_ID_S.nextval, sys_guid(), '1','10403',(SELECT RSP_ID FROM KRIM_RSP_T WHERE NM='Review PREQ Tax' AND OBJ_ID='UAF-6457-1'),'Y');
COMMIT;
INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,	OBJ_ID,	VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN) VALUES ('UAF-6457-RRA1','UAF-6457-RRA1','1','A','1','F','*',(SELECT ROLE_RSP_ID FROM KRIM_ROLE_RSP_T WHERE ROLE_ID = '10403' AND RSP_ID = (SELECT RSP_ID FROM KRIM_RSP_T WHERE NM='Review PREQ Tax' AND OBJ_ID='UAF-6457-1')) ,'Y');
COMMIT;

