-- =======================================================================================================================
-- UAF-3618 : Add Parm Values to DB Upgrade
-- =======================================================================================================================
UPDATE KRCR_NMSPC_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD = 'KUALI-TAX';

UPDATE KRCR_DRVD_CMPNT_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD='KUALI-TAX';

UPDATE KRCR_CMPNT_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD = 'KUALI-TAX';

UPDATE KRCR_PARM_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD = 'KUALI-TAX';

UPDATE KRCR_PARM_T
SET APPL_ID='KFS'
WHERE NMSPC_CD = 'KFS-TAX';

UPDATE KRIM_ROLE_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD = 'KUALI-TAX';

UPDATE KRIM_RSP_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD = 'KUALI-TAX';

UPDATE KRIM_PERM_T
SET NMSPC_CD='KFS-TAX'
WHERE NMSPC_CD = 'KUALI-TAX';

UPDATE KRIM_PERM_ATTR_DATA_T
SET ATTR_VAL='KFS-TAX'
WHERE ATTR_VAL='KUALI-TAX';

UPDATE KRIM_PERM_ATTR_DATA_T
SET ATTR_VAL='edu.arizona.kfs.module.tax.document.web.struts.ElectronicFilingReportAction'
WHERE PERM_ID='11293';

UPDATE KRIM_PERM_T
SET NM = REPLACE(NM, 'KUALI-TAX', 'KFS-TAX')
WHERE NM LIKE '%KUALI-TAX%';

UPDATE KRIM_PERM_T
SET DESC_TXT = REPLACE(DESC_TXT, 'KUALI-TAX', 'KFS-TAX')
WHERE DESC_TXT LIKE '%KUALI-TAX%';

INSERT INTO KRCR_CMPNT_T (NMSPC_CD, CMPNT_CD, OBJ_ID, VER_NBR, NM, ACTV_IND)
VALUES ('KFS-TAX', 'PayeeMasterExtractStep', SYS_GUID(), 1, 'Payee Master Extract Step', 'Y');