-- These were all problem children at one point or another, should stay fixed
CREATE UNIQUE INDEX KULOWNER.CM_CPTLAST_INV_UNIT_TI0 ON KULOWNER.CM_CPTLAST_INV_UNIT_T(INV_UNIT_CD, FIN_COA_CD, ORG_CD);
CREATE UNIQUE INDEX KULOWNER.FP_PMT_MTHD_CHART_TI8 ON KULOWNER.FP_PMT_MTHD_CHART_T(PMT_MTHD_CD, EFF_DT);
CREATE UNIQUE INDEX KULOWNER.PDP_SHIPPING_INV_TRACK_HIST_TI0 ON KULOWNER.PDP_SHIPPING_INV_TRACK_HIST_T(LOAD_DT,FILE_NM,INVOICE_NBR,TRACKING_NBR,SEQ_ROW_NBR);
CREATE UNIQUE INDEX KULOWNER.GL_REVERSAL_TI11 ON KULOWNER.GL_REVERSAL_T(FDOC_REVERSAL_DT,UNIV_FISCAL_YR,FIN_COA_CD,ACCOUNT_NBR, FIN_OBJECT_CD, FDOC_NBR);
CREATE INDEX KULOWNER.KREW_DOC_HDR_EXT_LONG_TI4 ON KULOWNER.KREW_DOC_HDR_EXT_LONG_T(DOC_HDR_ID);
CREATE INDEX KULOWNER.KREW_DOC_HDR_EXT_TI4 ON KULOWNER.KREW_DOC_HDR_EXT_T(DOC_HDR_ID);
CREATE UNIQUE INDEX KULOWNER.CA_ORG_EXT_T_TP1 ON KULOWNER.CA_ORG_EXT_T(FIN_COA_CD, ORG_CD);
